# Generated by Django 6.0 on 2026-04-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogconversiontask',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='blogconversiontask',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameIndex(
            model_name='blogconversiontask',
            new_name='task_blogco_user_id_7cfd31_idx',
            old_name='task_blogco_user_id_a74f90_idx',
        ),
        migrations.RenameIndex(
            model_name='blogconversiontask',
            new_name='task_blogco_blog_id_1606da_idx',
            old_name='task_blogco_blog_id_af89ad_idx',
        ),
    ]
